[beacon_db]
connection = "{databaseDir}cs-1.beacon.db"

[beaconing]
origination_interval = "5s"
propagation_interval = "5s"

[general]
id = "cs-1"
config_dir = "{configDir}"

[metrics]
prometheus = "127.0.0.1:30454"

[path_db]
connection = "{databaseDir}cs-1.path.db"


[trust_db]
connection = "{databaseDir}cs-1.trust.db"

[log.console]
level = "debug"

[api]
addr = "127.0.0.1:30554"

[ca]
mode = "delegating"

[ca.service]
shared_secret = "/root/AS150/config/client1.secret" # Update to your location
addr = "http://127.0.0.1:3000"                      # Point to caddys IP
client_id = "123"
